[package]
name = "guahao-game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
eframe = "0.29"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen-futures = "0.4"
